---
- shell: date +"%Y%m%d%H%M%S"
  register: version
- stat: path={{ deeeploy_project_path }}/current
  register: current_release
- file: state=touch
        path={{ deeeploy_project_path }}/current/{{ deeeploy_version_filename }}
  when: current_release.stat.exists
- command: chdir={{ deeeploy_project_path }}/current cat {{ deeeploy_version_filename }}
  register: old_commit
  when: current_release.stat.exists
- name: Commit déployé de la dernière release
  debug: var=old_commit.stdout_lines
  when: current_release.stat.exists
- command: git clone -b {{ deeeploy_branch }} {{ deeeploy_repo_url }} {{ deeeploy_project_path }}/releases/{{ version.stdout }}
- shell: chdir={{ deeeploy_project_path }}/releases/{{ version.stdout }} git rev-parse HEAD | cut -c1-8 > {{ deeeploy_version_filename }}
- name: Telechargement de composer
  shell: chdir={{ deeeploy_project_path }}/releases/{{ version.stdout }} curl -sS https://getcomposer.org/installer | {{ deeeploy_php_bin }}
  tags:
    - composer
- name: Initialisation du paramètre 'composer_env'
  set_fact:
    composer_env: 'dev'
  when: composer_env is undefined
  tags:
    - composer
- name: Génération des paramètres 'dev' de Composer
  set_fact:
    composer_options: '--prefer-dist --optimize-autoloader --no-interaction --no-progress --no-scripts'
  when: composer_env == 'dev'
  tags:
    - composer
- name: ou génération des paramètres 'prod' de Composer
  set_fact:
    composer_options: '--prefer-dist --no-dev --optimize-autoloader --no-interaction --no-progress --no-scripts'
  when: composer_env != 'dev'
  tags:
    - composer
- name: Installation des vendors
  command: chdir={{ deeeploy_project_path }}/releases/{{ version.stdout }} {{ deeeploy_php_bin }} composer.phar install {{ composer_options }}
  tags:
    - composer
- name: Copie des fichiers de config
  template: src=../{{ item }}.dist dest={{ deeeploy_project_path }}/releases/{{ version.stdout }}/{{ item }}
  with_items: deeeploy_config_files
- file: state=absent
        path={{ deeeploy_project_path }}/releases/{{ version.stdout }}/{{ item }}
  with_items: deeeploy_shared_files
- name: Symlink des fichiers partagés
  file: state=link
        src={{ deeeploy_project_path }}/shared/{{ item }}
        dest={{ deeeploy_project_path }}/releases/{{ version.stdout }}/{{ item }}
  with_items: deeeploy_shared_files
- name: Execution du script shell custom
  shell: chdir={{ deeeploy_project_path }}/releases/{{ version.stdout }} ./{{ deeeploy_custom_shell_script }}
  when: deeeploy_custom_shell_script is defined
- command: chdir={{ deeeploy_project_path }}/releases/{{ version.stdout }} cat {{ deeeploy_version_filename }}
  register: new_commit
- shell: chdir={{ deeeploy_project_path }}/releases/{{ version.stdout }} git --no-pager log --no-merges --oneline {{ old_commit.stdout }}...{{ new_commit.stdout }}
  register: changelog
  when: deeeploy_newrelic_token is defined
- name: Suppression des fichiers inutiles
  file: state=absent
        path={{ deeeploy_project_path }}/releases/{{ version.stdout }}/{{ item }}
  with_items: deeeploy_clean_files
- name: Création du symlink
  file: state=link
        src={{ deeeploy_project_path }}/releases/{{ version.stdout }}
        dest={{ deeeploy_project_path }}/current
        force=yes
- newrelic_deployment: token={{ deeeploy_newrelic_token }}
                       application_id={{ deeeploy_newrelic_app_id }}
                       user='Ansible'
                       revision="{{ deeeploy_branch }} - {{ new_commit.stdout }}"
                       changelog="{{ changelog.stdout }}"
  when: deeeploy_newrelic_token is defined
- name: Notification Slack
  slack:
    token: "{{ deeeploy_slack_token }}"
    channel: "{{ deeeploy_slack_channel }}"
    username: "Ansible"
    msg: "Deploy to {{ inventory_hostname }}\nbranch : {{ deeeploy_branch }}\nhash : {{ new_commit.stdout }}\nchangelog :\n{{ changelog.stdout }}"
  when: deeeploy_slack_token is defined
